[package]
name = "lxx-calendar-quotes"
version = "0.1.0"
edition.workspace = true

[build-dependencies]
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
