[package]
name = "lxx-calendar-boards-tspi"
version = "0.1.0"
edition.workspace = true

[features]
default = ["tspi"]
tspi = []

[dependencies]
lxx-calendar-common = { path = "../../lxx-calendar-common" }
lxx-calendar-core = { path = "../../lxx-calendar-core" }
static_cell = { workspace = true }
simulated-wdt = { path = "../../libs/simulated-wdt" }
epd-yrd0750ryf665f60 = { version = "0.1.0", path = "../../libs/epd" }

[dependencies.embassy-sync]
workspace = true

[dependencies.embassy-time]
workspace = true

[dependencies.embassy-executor]
workspace = true
features = ["arch-std"]

[dependencies.linux-embedded-hal]
git = "https://github.com/rust-embedded/linux-embedded-hal.git"
features = ["gpio_sysfs", "spi", "async-tokio"]
