[target.riscv32imac-unknown-none-elf]
runner = "probe-rs run --chip=esp32c6 --preverify --always-print-stacktrace --no-location --catch-hardfault"
rustflags = [
    "-C",
    "force-frame-pointers",
    "--cfg",
    'getrandom_backend="custom"',
]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[env]
ESP_LOG = "INFO"

[alias]
# Linux相关命令
btspi = "build -p lxx-calendar-boards-tspi --target aarch64-unknown-linux-gnu --no-default-features --features tspi"
btspir = "build -p lxx-calendar-boards-tspi --release --target aarch64-unknown-linux-gnu --no-default-features --features tspi"

ctspi = "check -p lxx-calendar-boards-tspi --target aarch64-unknown-linux-gnu --no-default-features --features tspi"

# 模拟器相关命令
bs = "build -p lxx-calendar-boards-simulator --target x86_64-unknown-linux-gnu --no-default-features --features simulator"
bsr = "build -p lxx-calendar-boards-simulator --target x86_64-unknown-linux-gnu --no-default-features --release --features simulator"

bsg = "build -p lxx-calendar-boards-simulator --target x86_64-unknown-linux-gnu --no-default-features --features simulator --features embedded_graphics_simulator"
bsgr = "build -p lxx-calendar-boards-simulator --target x86_64-unknown-linux-gnu --release --no-default-features --features simulator --features embedded_graphics_simulator"

rs = "run -p lxx-calendar-boards-simulator --target x86_64-unknown-linux-gnu --no-default-features --features simulator"
rsr = "run -p lxx-calendar-boards-simulator --target x86_64-unknown-linux-gnu --no-default-features --release --features simulator"

rsg = "run -p lxx-calendar-boards-simulator --target x86_64-unknown-linux-gnu --no-default-features --features simulator --features embedded_graphics_simulator"
rsgr = "run -p lxx-calendar-boards-simulator --target x86_64-unknown-linux-gnu --no-default-features --release --features simulator --features embedded_graphics_simulator"

cs = "check -p lxx-calendar-boards-esp32c6 --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"

# ESP32C6相关命令
besp = "build -p lxx-calendar-boards-esp32c6 --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
bespr = "build -p lxx-calendar-boards-esp32c6 --release --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"

cesp = "check -p lxx-calendar-boards-esp32c6 --target riscv32imac-unknown-none-elf --no-default-features --features esp32c6"
