[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[alias]
bel = "build --target aarch64-unknown-linux-gnu --features embedded_linux"
belr = "build --release --target aarch64-unknown-linux-gnu --features embedded_linux"
bs = "build --features simulator"
bsr = "build --release --features simulator"
rs = "run --features simulator"
rrs = "run --release --features simulator"